openapi: 3.0.1
info:
  title: Mobi Agent Trip Planner Plugin
  description: Plugin for planning an travel itinerary. You can set the origin origin, trip destination, dates, travelers, as well as preferences on stay, dining, experiences and flights..
  version: 'v1'
servers:
  - url: https://fareportal-staging.takemobi.io
paths:
  /mobility-planner/demo/v2/problem/chatgpt:
    post:
      operationId: createItinerary
      summary: Create a travel itinerary
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItineraryRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItineraryResponse'
components:
  schemas:
    ItineraryRequest:
      type: object
      properties:
        trip_start_datetime:
          type: string
          format: date-time
          description: The start date time of the trip, following the date-time notation as defined by RFC 3339, section 5.6. For example, 2017-07-21T17:32:28Z.
        trip_end_datetime:
          type: string
          format: date-time
          description: The end date time of the trip, following the date-time notation as defined by RFC 3339, section 5.6. For example, 2017-08-21T17:32:28Z.
        origin_name:
          type: string
          description: The name of the origin of the trip.
        origin_lat:
          type: number
          minimum: -90
          maximum: 90
          description: The latitude of the origin location of the trip.
        origin_lng:
          type: number
          minimum: -180
          maximum: 180
          description: The longitude of the origin location of the trip.
        destination_name:
          type: string
          description: The name of the destination of the trip.
        destination_lat:
          type: number
          minimum: -90
          maximum: 90
          description: The latitude of the destination location of the trip.
        destination_lng:
          type: number
          minimum: -180
          maximum: 180
          description: The longitude of the destination location of the trip.
        traveler_information:
          $ref: '#/components/schemas/TravelerInformation'
          description: Information on the number of travelers of different types in this trip.
        selected_accommodation_tags:
          type: array
          items: {
            type: string,
            enum: [
              "Hotel",
              "Motel",
              "Hotel Resort",
              "Inn",
              "Bed & Breakfast",
              "Guest House",
              "Condo",
              "All-Inclusive",
              "Cabin",
              "Chalet",
              "Cottage",
              "Ranch",
              "Villa",
              "Lodge",
              "Apartment",
              "Private Vacation Home",
              "House Boat",
              "Ryokan",
              "Tree House",
              "Apart-hotel",
              "Condominium Resort",
              "Caravan Park",
              "Riad",
              "Country House",
              "Pension",
              "Residence",
              "TownHouse",
              "Castle",
              "Palace",
              "5 star hotel",
              "4.5 star hotel",
              "4 star hotel",
              "3.5 star hotel",
              "3 star hotel",
              "2.5 star hotel",
              "2 star hotel"
            ]
          }
          description: A list of accommodation related tags that describe the desired accommodation options in the trip.
        selected_activity_tags:
          type: array
          items: {
            type: string,
            enum: [
              "Scuba diving",
              "Photoshoot",
              "People watching",
              "Fishing",
              "Amusement park",
              "Massage & spa",
              "Museum",
              "Picnic",
              "Hot spring",
              "Snorkeling",
              "Skiing",
              "Ice skating",
              "Walking",
              "Food & drinks",
              "Karaoke",
              "Fireworks",
              "Sky diving",
              "Trip",
              "Food & tasting",
              "Rock climbing",
              "Hiking",
              "Swimming",
              "Dancing",
              "Biking",
              "Lazer shooting game",
              "Jogging",
              "Escape room"
            ]
          }
          description: A list of activity related tags that describe the desired activities to plan for the trip.
        selected_dining_tags:
          type: array
          items: {
            type: string,
            enum: [
              "Bib Gourmand",
              "One MICHELIN Star",
              "Two MICHELIN Stars",
              "Three MICHELIN Stars",
              "The MICHELIN Plate",
              "Breakfast",
              "Late Night",
              "Drinks",
              "Lunch",
              "Dinner",
              "Beach",
              "Buffet",
              "Family Style",
              "Jazz Bar",
              "Live Music",
              "Non-smoking restaurants",
              "Outdoor Seating",
              "Waterfront",
              "Wheelchair Accessible",
              "Halal",
              "Vegan Options",
              "Gluten Free Options",
              "Vegetarian Friendly",
              "Kosher",
              "Sit down",
              "Fast food",
              "Cafe",
              "Bar",
              "Pub",
              "Steakhouse",
              "Deli",
              "Grill",
              "Diner",
              "Gastropub",
              "Brew Pub",
              "Dining bars",
              "Beer restaurants"
            ]
          }
          description: A list of food and dining related tags that describe the desired dining options to plan for the trip.
        selected_flight_tags:
          type: array
          items: {
            type: string,
            enum: [
              "Economy",
              "Premium Economy",
              "Business",
              "First",
              "Non-stop",
              "One-stop",
              "Two-stop"
            ]
          }
          description: A list of flight related tags that describe the desired flight options in the trip.
      required:
        - trip_start_datetime
        - trip_end_datetime
        - origin_name
        - origin_lat
        - origin_lng
        - destination_name
        - destination_lat
        - destination_lng
    ItineraryResponse:
      type: object
      properties:
        solution:
          $ref: '#/components/schemas/ItinerarySolution'
          description: The detailed solution object to the itinerary request.
        deeplink:
          type: string
          description: The url to a webpage in which users can view and further customize the trip.
    ItinerarySolution:
      type: object
      properties:
        activities:
          type: array
          items:
            $ref: '#/components/schemas/ItineraryActivity'
          description: The planned activities in the itinerary solution.
      required:
        - activities
    ItineraryActivity:
      type: object
      properties:
        name:
          type: string
          description: The name of the activity.
        scheduled_start_time:
          type: integer
          format: int64
          description: The scheduled start time of the activity in UNIX timestamp.
        scheduled_end_time:
          type: integer
          format: int64
          description: The scheduled end time of the activity in UNIX timestamp.
        source:
          $ref: '#/components/schemas/Source'
          description: The source object for the activity in the solution.
      required:
        - name
        - scheduled_start_time
        - scheduled_end_time
    TravelerInformation:
      type: object
      properties:
        adults:
          type: integer
          minimum: 1
          maximum: 9
          description: The number of adults (age 18 or higher) in the trip.
        children:
          type: integer
          minimum: 1
          maximum: 9
          description: The number of children (age 2 to 17) in the trip.
        infants:
          type: integer
          minimum: 1
          maximum: 4
          description: The number of infants (under age 2) in the trip.
      required:
        - adults
    TripLocation:
      type: object
      properties:
        name:
          type: string
          description: The name of the location.
        lat:
          type: number
          minimum: -90
          maximum: 90
          description: The latitude of the location.
        lng:
          type: number
          minimum: -180
          maximum: 180
          description: The longitude of the location.
      required:
        - name
        - lat
        - lng
    Source:
      type: object
      properties:
        content:
          $ref: '#/components/schemas/Content'
          description: The content object for the activity in the itinerary.
    Content:
      type: object
      properties:
        website:
          type: string
          description: The url to the activity's website.
        booking_url:
          type: string
          description: The booking link for booking this activity.